[project]
name="causal_testing_walkthrough"
requires-python=">=3.12"
dependencies = [
    "covasim>=3.1.8",
    "jupyter>=1.1.1",
    "rise>=5.7.1",
    "nbstripout",
    "pre-commit",
    "pygraphviz",
    "holoviews",
    "black",
    "causal_testing_framework @ git+https://github.com/CITCOM-project/CausalTestingFramework@2c8e9514ace56f0df2847e05cc6675152f58aa99"
]
dynamic=["version"]
